///////////////////////////////////////////////////////////////////////////////
// ControllerInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ControllerServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
