///////////////////////////////////////////////////////////////////////////////
// ControllerServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Controller = 0x3F000000;
#define SRVNAME_CONTROLLER "Controller"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ControllerCModule = {0xce1e09ae,0x8d1e,0x4d99,{0x88,0x5e,0x74,0xac,0xc8,0xe2,0x0a,0x4f}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleMotorStArea 0
#define ADI_ModuleMotorCmdArea 1
#define ADI_ModuleServerToClient 3
#define ADI_ModuleClientToServer 4
#define ADI_ModuleLogBuf 5
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleDefaultAdsPort = 0x00000001;
const PTCID PID_ModuleCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_77087501_4F64_4602_BB81_9A2E10B2B53C_INCLUDED_)
#define _TC_TYPE_77087501_4F64_4602_BB81_9A2E10B2B53C_INCLUDED_
#pragma pack(push,1)
typedef struct _MotorSt
{
	USHORT nStatusWord;
	LONG nActualPosition;
	LONG nActualVelocity;
	SHORT nActualTorque;
	USHORT nErrorCode;
	char nModeOfOperationDisp;
	bool nWcState;
} MotorSt, *PMotorSt;
#pragma pack(pop)
const GUID GUID_MotorSt = {0x77087501, 0x4F64, 0x4602, {0xBB, 0x81, 0x9A, 0x2E, 0x10, 0xB2, 0xB5, 0x3C}};
#endif // !defined(_TC_TYPE_77087501_4F64_4602_BB81_9A2E10B2B53C_INCLUDED_)

#if !defined(_TC_TYPE_A3FE36B3_941D_4A02_B96F_4DB374FA48BA_INCLUDED_)
#define _TC_TYPE_A3FE36B3_941D_4A02_B96F_4DB374FA48BA_INCLUDED_
#pragma pack(push,1)
typedef struct _MotorCmd
{
	USHORT nControlWord;
	LONG nTargetPosition;
	LONG nTargetVelocity;
	SHORT nTargetTorque;
	USHORT nMaxTorque;
	char nModeOfOperation;
} MotorCmd, *PMotorCmd;
#pragma pack(pop)
const GUID GUID_MotorCmd = {0xA3FE36B3, 0x941D, 0x4A02, {0xB9, 0x6F, 0x4D, 0xB3, 0x74, 0xFA, 0x48, 0xBA}};
#endif // !defined(_TC_TYPE_A3FE36B3_941D_4A02_B96F_4DB374FA48BA_INCLUDED_)

#if !defined(_TC_TYPE_1AE64861_8E32_4909_BED8_5D485F4D3A8B_INCLUDED_)
#define _TC_TYPE_1AE64861_8E32_4909_BED8_5D485F4D3A8B_INCLUDED_
#pragma pack(push,1)
typedef struct _PathParameter
{
	double nTotalTime;
	double nStepSize;
	double nAccTime;
	USHORT nProfileMode;
	bool nUpdate;
	LONG nSetPosition;
} PathParameter, *PPathParameter;
#pragma pack(pop)
const GUID GUID_PathParameter = {0x1AE64861, 0x8E32, 0x4909, {0xBE, 0xD8, 0x5D, 0x48, 0x5F, 0x4D, 0x3A, 0x8B}};
#endif // !defined(_TC_TYPE_1AE64861_8E32_4909_BED8_5D485F4D3A8B_INCLUDED_)

#if !defined(_TC_TYPE_AA135F34_E5F8_4BC8_BC68_2F5AB0625287_INCLUDED_)
#define _TC_TYPE_AA135F34_E5F8_4BC8_BC68_2F5AB0625287_INCLUDED_
typedef struct _JogParameter
{
	USHORT nJogID;
	USHORT nJogTick;
} JogParameter, *PJogParameter;
const GUID GUID_JogParameter = {0xAA135F34, 0xE5F8, 0x4BC8, {0xBC, 0x68, 0x2F, 0x5A, 0xB0, 0x62, 0x52, 0x87}};
#endif // !defined(_TC_TYPE_AA135F34_E5F8_4BC8_BC68_2F5AB0625287_INCLUDED_)

#pragma pack(push,1)
typedef struct _ModuleMotorStArea
{
	MotorSt Data[15];
} ModuleMotorStArea, *PModuleMotorStArea;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleMotorCmdArea
{
	MotorCmd Data[15];
} ModuleMotorCmdArea, *PModuleMotorCmdArea;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleServerToClient
{
	MotorSt DataMotorSt[15];
	MotorCmd DataMotorCmd[15];
} ModuleServerToClient, *PModuleServerToClient;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleClientToServer
{
	USHORT MainCmd;
	USHORT SubCmd;
	PathParameter PathCmd[15];
	JogParameter JogCmd;
	USHORT ClientHeartBeat;
} ModuleClientToServer, *PModuleClientToServer;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleLogBuf
{
	bool Flag;
	MotorSt MotorStBuf[200][15];
	MotorCmd MotorCmdBuf[200][15];
} ModuleLogBuf, *PModuleLogBuf;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
