///////////////////////////////////////////////////////////////////////////////
// ControllerClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ControllerClassFactory.h"
#include "ControllerServices.h"
#include "ControllerVersion.h"
#include "Module.h"

BEGIN_CLASS_MAP(CControllerClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_Controller, CID_ControllerCModule, SRVNAME_CONTROLLER "!CModule", CModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CControllerClassFactory::CControllerClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_CONTROLLER));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Controller));
#endif //defined(TCDBG_UNIT_VERSION)
}

