///////////////////////////////////////////////////////////////////////////////
// Module.h
#pragma once

#include "ControllerInterfaces.h"
#include "AdsR0.h"

#include "humanoid_common/motor_count.h"

// parameter ids for TwinCAT module Module with disabled code generation
// could be moved to ControllerServices.h
const PTCID PID_ModuleAdsPort        = 0x00000002;

// Lower-body active motor count, mirrored from
// humanoid_common::motor_count::kLowerBodyMotors as a plain int so it can
// size CModule member arrays below. The reference's 31-motor bound is
// intentionally NOT used.
static constexpr int kLowerMotorCount = static_cast<int>(humanoid_common::motor_count::kLowerBodyMotors);

/// Values stored in ModuleClientToServer.MainCmd / .SubCmd (USHORT in PLC).
/// Numeric values must stay byte-identical to the historical 31-motor
/// reference module so PLC code that uses these enums keeps working, and
/// also identical to TcUpperBodyController so a single PLC vocabulary
/// drives both controllers.
namespace ClientCommand
{
	enum class Main : USHORT
	{
		ControlDrive = 1,
		SetOperationMode = 2,
		PathMotion = 3,
		JogModeMove = 4,
	};

	/// SubCmd when Main == ControlDrive
	enum class DriveSub : USHORT
	{
		EnableSequence = 1,
		QuitStep = 2,
		FaultReset = 3,
	};

	/// SubCmd when Main == SetOperationMode (CiA 402 cyclic modes)
	enum class ModeSub : USHORT
	{
		Csp = 1,
		Csv = 2,
		Cst = 3,
	};

	/// SubCmd when Main == PathMotion. Values kept byte-identical to the
	/// historical 31-motor reference so PLC code that uses these enums
	/// keeps working. Dispatched by CModule::ApplyPathMotion().
	enum class PathSub : USHORT
	{
		TrapezoidalProfile = 1,
		QuinticPolynomial = 2,
		PlayPath = 3,
		Reciprocate = 4,
		SteppingOffsetMove = 5,
		StopHoldAndResetPath = 6,
		Pause = 7,
		Resume = 8,
	};

	/// SubCmd when Main == JogModeMove (CSP only)
	enum class JogSub : USHORT
	{
		Positive = 1,
		Negative = 2,
		Stop = 3,
	};
}

class CModule 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
	, public CAdsR0FifoPort
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModule();
	virtual	~CModule();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

	// CAds
	virtual	void	AdsReadWriteInd
	(
		AmsAddr& rAddr, 
		ULONG invokeId, 
		ULONG indexGroup,
		ULONG indexOffset, 
		ULONG cbReadLength, 
		ULONG cbWriteLength, 
		PVOID pData 
	);

	virtual void AdsReadCon
	(
		AmsAddr& rAddr, 
		ULONG invokeId, 
		ULONG result, 
		ULONG cbLength, 
		PVOID pData
	);

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Cycle dispatch from ModuleClientToServer.MainCmd / .SubCmd. Loops only
	// over the active lower-body motor count (kLowerMotorCount == 15); does
	// NOT use the 31-motor reference loop bound. Forwards Main::PathMotion
	// to ApplyPathMotion().
	void ApplyMainCmdMotorOutputs();

	// Safety override applied after command dispatch each cycle. Forces
	// CiA 402 Shutdown (ControlWord 0x0006) and ModeOfOperation 0 on any
	// motor whose drive is offline (nWcState true == power / communication
	// lost), overriding whatever the command path wrote that cycle.
	void ApplySafetyOverrides();

	// Path-motion sub-dispatch (Main::PathMotion). Runs the per-motor
	// trajectory state machines (one-shot trapezoidal / quintic, reciprocate,
	// stepping offset) and the playback opcodes (PlayPath, Pause, Resume,
	// StopHoldAndResetPath). Loops only over the active lower-body motor
	// count; uses humanoid::motion::* helpers exclusively.
	void ApplyPathMotion();

	// Per-cycle ring-buffer logger. Writes one row of motor state and one
	// row of motor command into m_LoggingBuffer.Data, advances the write
	// index modulo the TMC-declared depth (200), and toggles
	// m_LoggingBuffer.Data.Flag at the half-fill (idx == 99) boundary so
	// PLC / HMI clients can read a stable half of the buffer while the
	// other half is being written. Row sizes are taken from sizeof() of
	// the generated 2-D arrays so hard-coded motor counts are not needed.
	void UpdateLoggingBuffer();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	WORD m_DefaultAdsPort;
	WORD m_ContextAdsPort;
	ULONG m_Counter;
	ModuleMotorStArea m_MotorStArea;
	ModuleMotorCmdArea m_MotorCmdArea;
	ModuleServerToClient m_ServerToClient;
	ModuleClientToServer m_ClientToServer;
	ModuleLogBuf m_LogBuf;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	// Path motion state (MainCmd == PathMotion); analytic playback, no
	// stored path buffer. All arrays are sized by the active lower-body
	// motor count (kLowerMotorCount == 15); never the reference's 31.
	LONG m_trajStep[kLowerMotorCount];
	int m_trajLength[kLowerMotorCount];
	double m_trajX0[kLowerMotorCount];
	double m_trajXf[kLowerMotorCount];
	double m_trajTf[kLowerMotorCount];
	double m_trajTa[kLowerMotorCount];
	double m_trajH[kLowerMotorCount];
	bool m_trajIsTrapezoid[kLowerMotorCount];
	bool m_trajValid[kLowerMotorCount];
	bool m_trajPaused[kLowerMotorCount];
	bool m_prevPathNUpdate[kLowerMotorCount];
	LONG m_trajLastTargetPos[kLowerMotorCount];
	USHORT m_prevPathMotionSub;

	// Reciprocate (PathSub::Reciprocate): A <-> B per axis
	bool m_recipValid[kLowerMotorCount];
	bool m_recipForward[kLowerMotorCount];
	LONG m_recipPosStart[kLowerMotorCount];
	LONG m_recipPosTarget[kLowerMotorCount];
	int m_recipLegStep[kLowerMotorCount];
	int m_recipLegLength[kLowerMotorCount];
	double m_recipTf[kLowerMotorCount];
	double m_recipH[kLowerMotorCount];
	double m_recipTa[kLowerMotorCount];
	bool m_recipUseTrapezoid[kLowerMotorCount];

	// SteppingOffsetMove (PathSub::SteppingOffsetMove): segment to segXf,
	// then segXf += delta each completion.
	bool m_stepOffValid[kLowerMotorCount];
	LONG m_stepOffDelta[kLowerMotorCount];
	double m_stepOffSegX0[kLowerMotorCount];
	double m_stepOffSegXf[kLowerMotorCount];
	int m_stepOffLegStep[kLowerMotorCount];
	int m_stepOffLegLen[kLowerMotorCount];
	double m_stepOffTf[kLowerMotorCount];
	double m_stepOffH[kLowerMotorCount];
	double m_stepOffTa[kLowerMotorCount];
	bool m_stepOffUseTrap[kLowerMotorCount];

	/// Next LoggingBuffer row index (0 .. kLogBufferDepth - 1). Not exposed
	/// on ADS; advanced by UpdateLoggingBuffer() once per cycle.
	int m_logWriteIndex;

	void SubmitAdsReadReq();
	enum 
	{
		invokeIdReadByOidAndPid = 1
	};
	ULONG  m_ReadByOidAndPid;
};
