///////////////////////////////////////////////////////////////////////////////
// ControllerServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Controller = 0x3F000000;
#define SRVNAME_CONTROLLER "Controller"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ControllerCModule = {0x16f9dee6,0x349d,0x4d62,{0x85,0x18,0x63,0x1c,0xde,0x30,0xd0,0x20}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleMotorStArea 0
#define ADI_ModuleMotorCmdArea 1
#define ADI_ModuleServerToClient 3
#define ADI_ModuleClientToServer 4
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleDefaultAdsPort = 0x00000001;
const PTCID PID_ModuleCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_601F8B49_CF5A_4228_BF1A_01B2B3D32656_INCLUDED_)
#define _TC_TYPE_601F8B49_CF5A_4228_BF1A_01B2B3D32656_INCLUDED_
#pragma pack(push,1)
typedef struct _MotorSt
{
	USHORT nStatusWord;
	LONG nActualPosition;
	LONG nActualVelocity;
	SHORT nActualTorque;
	USHORT nErrorCode;
	char nModeOfOperationDisp;
} MotorSt, *PMotorSt;
#pragma pack(pop)
const GUID GUID_MotorSt = {0x601F8B49, 0xCF5A, 0x4228, {0xBF, 0x1A, 0x01, 0xB2, 0xB3, 0xD3, 0x26, 0x56}};
#endif // !defined(_TC_TYPE_601F8B49_CF5A_4228_BF1A_01B2B3D32656_INCLUDED_)

#if !defined(_TC_TYPE_8674A5C4_6BF0_4D3A_BD40_9951B6BB49CA_INCLUDED_)
#define _TC_TYPE_8674A5C4_6BF0_4D3A_BD40_9951B6BB49CA_INCLUDED_
#pragma pack(push,1)
typedef struct _MotorCmd
{
	USHORT nControlWord;
	LONG nTargetPosition;
	LONG nTargetVelocity;
	SHORT nTargetTorque;
	USHORT nMaxTorque;
	char nModeOfOperation;
} MotorCmd, *PMotorCmd;
#pragma pack(pop)
const GUID GUID_MotorCmd = {0x8674A5C4, 0x6BF0, 0x4D3A, {0xBD, 0x40, 0x99, 0x51, 0xB6, 0xBB, 0x49, 0xCA}};
#endif // !defined(_TC_TYPE_8674A5C4_6BF0_4D3A_BD40_9951B6BB49CA_INCLUDED_)

#if !defined(_TC_TYPE_4AA9B062_E444_4AFA_967D_37D3B6A3E217_INCLUDED_)
#define _TC_TYPE_4AA9B062_E444_4AFA_967D_37D3B6A3E217_INCLUDED_
#pragma pack(push,1)
typedef struct _PathParameter
{
	double nTotalTime;
	double nStepSize;
	bool nUpdate;
	LONG nSetPoint;
} PathParameter, *PPathParameter;
#pragma pack(pop)
const GUID GUID_PathParameter = {0x4AA9B062, 0xE444, 0x4AFA, {0x96, 0x7D, 0x37, 0xD3, 0xB6, 0xA3, 0xE2, 0x17}};
#endif // !defined(_TC_TYPE_4AA9B062_E444_4AFA_967D_37D3B6A3E217_INCLUDED_)

#if !defined(_TC_TYPE_B091FF8A_C150_4574_A5A8_7F2C8421800E_INCLUDED_)
#define _TC_TYPE_B091FF8A_C150_4574_A5A8_7F2C8421800E_INCLUDED_
typedef struct _JogParameter
{
	USHORT nJogIP;
	USHORT nJogTick;
} JogParameter, *PJogParameter;
const GUID GUID_JogParameter = {0xB091FF8A, 0xC150, 0x4574, {0xA5, 0xA8, 0x7F, 0x2C, 0x84, 0x21, 0x80, 0x0E}};
#endif // !defined(_TC_TYPE_B091FF8A_C150_4574_A5A8_7F2C8421800E_INCLUDED_)

#pragma pack(push,1)
typedef struct _ModuleMotorStArea
{
	MotorSt Data;
} ModuleMotorStArea, *PModuleMotorStArea;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleMotorCmdArea
{
	MotorCmd Data;
} ModuleMotorCmdArea, *PModuleMotorCmdArea;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleServerToClient
{
	MotorSt DataMotorSt;
	MotorCmd DataMotorCmd;
} ModuleServerToClient, *PModuleServerToClient;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleClientToServer
{
	USHORT MainCmd;
	USHORT SubCmd;
	PathParameter PathCmd;
	JogParameter JogCmd;
} ModuleClientToServer, *PModuleClientToServer;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
