///////////////////////////////////////////////////////////////////////////////
// Module.cpp
#include "TcPch.h"
#pragma hdrstop

#include "Module.h"
#include "ModuleAds.h"
#include "ControllerVersion.h"

// Shared header-only libraries. Pure C++; independent from TwinCAT/TcCOM/
// TMC/ADS/EtherCAT headers. Resolved via this project's
// AdditionalIncludeDirectories entries (..\..\..\common\humanoid_common\include
// and ..\..\..\common\humanoid_motion\include).
//
// IMPORTANT: this project's Controller.vcxproj does NOT yet carry those two
// include directories for the build platform (Release|TwinCAT OS (x64-E)).
// They must be added there before this file compiles. See the handover note.
#include "humanoid_common/cia402.h"
#include "humanoid_motion/trajectory_profile.h"

namespace {

// Trapezoidal acceleration time as a fraction of total time. This module's
// PathParameter has no nAccTime field, so the trapezoidal profile derives the
// blend time from the requested total time. Clamped to [0, tf*0.5] downstream.
constexpr double kDefaultAccelRatio = 0.3;

}  // namespace

// Compile-time sanity on the shared CiA 402 mode constants.
static_assert(humanoid::cia402::kModeCsp == 8, "CSP mode value must be 8");
static_assert(humanoid::cia402::kModeCsv == 9, "CSV mode value must be 9");
static_assert(humanoid::cia402::kModeCst == 10, "CST mode value must be 10");

///////////////////////////////////////////////////////////////////////////////
// CModule
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CModule
BEGIN_INTERFACE_MAP(CModule)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CModule, VID_Controller, CID_ControllerCModule)
IMPLEMENT_ITCOMOBJECT(CModule)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CModule)
IMPLEMENT_ITCADI(CModule)
IMPLEMENT_ITCWATCHSOURCE(CModule)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CModule 
BEGIN_SETOBJPARA_MAP(CModule)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_ModuleDefaultAdsPort, m_DefaultAdsPort)
	SETOBJPARA_VALUE(PID_Ctx_AdsPort, m_ContextAdsPort)
	SETOBJPARA_VALUE(PID_ModuleCounter, m_Counter)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CModule 
BEGIN_GETOBJPARA_MAP(CModule)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_ModuleDefaultAdsPort, m_DefaultAdsPort)
	GETOBJPARA_VALUE(PID_Ctx_AdsPort, m_ContextAdsPort)
	GETOBJPARA_VALUE(PID_ModuleCounter, m_Counter)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
	GETOBJPARA_TYPE_CODE(PID_ModuleAdsPort, WORD, *p = AmsGetPort())
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CModule
BEGIN_OBJPARAWATCH_MAP(CModule)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
	OBJPARAWATCH_VALUE(PID_ModuleCounter, m_Counter)
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CModule
BEGIN_OBJDATAAREA_MAP(CModule)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_ModuleMotorStArea, m_MotorStArea)
	OBJDATAAREA_VALUE(ADI_ModuleMotorCmdArea, m_MotorCmdArea)
	OBJDATAAREA_VALUE(ADI_ModuleServerToClient, m_ServerToClient)
	OBJDATAAREA_VALUE(ADI_ModuleClientToServer, m_ClientToServer)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CModule::CModule()
	: m_Trace(m_TraceLevelMax, m_spSrv)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	m_DefaultAdsPort = 0;
	m_ContextAdsPort = 0;
	m_Counter = 0;
	memset(&m_MotorStArea, 0, sizeof(m_MotorStArea));
	memset(&m_MotorCmdArea, 0, sizeof(m_MotorCmdArea));
	memset(&m_ServerToClient, 0, sizeof(m_ServerToClient));
	memset(&m_ClientToServer, 0, sizeof(m_ClientToServer));
///</AutoGeneratedContent>

	// Deterministic initialisation of all path-motion state. These members are
	// not covered by the auto-generated memset block above.
	m_trajStep = 0;
	m_trajLength = 0;
	m_trajX0 = 0.0;
	m_trajXf = 0.0;
	m_trajTf = 0.0;
	m_trajTa = 0.0;
	m_trajH = 0.0;
	m_trajIsTrapezoid = false;
	m_trajValid = false;
	m_trajPaused = false;
	m_prevPathNUpdate = false;
	m_trajLastTargetPos = 0;
	m_prevPathMotionSub = 0;

	m_recipValid = false;
	m_recipForward = false;
	m_recipPosStart = 0;
	m_recipPosTarget = 0;
	m_recipLegStep = 0;
	m_recipLegLength = 0;
	m_recipTf = 0.0;
	m_recipH = 0.0;
	m_recipTa = 0.0;
	m_recipUseTrapezoid = false;

	m_stepOffValid = false;
	m_stepOffDelta = 0;
	m_stepOffSegX0 = 0.0;
	m_stepOffSegXf = 0.0;
	m_stepOffLegStep = 0;
	m_stepOffLegLen = 0;
	m_stepOffTf = 0.0;
	m_stepOffH = 0.0;
	m_stepOffTa = 0.0;
	m_stepOffUseTrap = false;

	m_commandedMode = -1;
}

///////////////////////////////////////////////////////////////////////////////
CModule::~CModule() 
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CModule)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CModule::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	hr = SUCCEEDED(hr) ? InitAmsPort(m_spSrv, m_DefaultAdsPort) : hr;

	// cleanup on failure
	if (FAILED(hr))
	{
		ShutdownAmsPort();
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CModule::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization


	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before this method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CModule::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CModule::SetObjStateSP()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	HRESULT hr = S_OK;
	ShutdownAmsPort();

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CModule::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// handle pending ADS indications and confirmations
	CheckOrders();

	// Mirror the EtherCAT-driven motor state into the ADS-visible area, run the
	// active command dispatch, then publish the patched motor command area.
	// ApplyMainCmdMotorOutputs() only patches selected command fields.
	m_ServerToClient.DataMotorSt = m_MotorStArea.Data;
	ApplyMainCmdMotorOutputs();
	m_ServerToClient.DataMotorCmd = m_MotorCmdArea.Data;

	// TODO: Submit your ADS requests 
	ULONGLONG cnt = 0;
	if (SUCCEEDED(ipTask->GetCycleCounter(&cnt)))
	{
		if (cnt%100 == 0)
		{
			SubmitAdsReadReq();
		}
	}

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CModule::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CModule::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
	m_Trace.Log(tlVerbose, FLEAVEA_STR());
}

///////////////////////////////////////////////////////////////////////////////
// Per-cycle dispatch for Main::PathMotion on the single motor. Trajectory
// primitives come from humanoid::motion::* (header-only).
//
// This module's PathParameter has no nAccTime and no nProfileMode field, so the
// trapezoidal acceleration time uses kDefaultAccelRatio (clamped to
// [0, tf*0.5]) and reciprocate / stepping-offset always use the quintic blend.
void CModule::ApplyPathMotion()
{
	const USHORT subRaw = m_ClientToServer.SubCmd;
	const auto sub = static_cast<ClientCommand::PathSub>(subRaw);

	const bool firstTrapezoidal =
		(sub == ClientCommand::PathSub::TrapezoidalProfile)
		&& (m_prevPathMotionSub != static_cast<USHORT>(ClientCommand::PathSub::TrapezoidalProfile));
	const bool firstQuintic =
		(sub == ClientCommand::PathSub::QuinticPolynomial)
		&& (m_prevPathMotionSub != static_cast<USHORT>(ClientCommand::PathSub::QuinticPolynomial));
	const bool firstReciprocate =
		(sub == ClientCommand::PathSub::Reciprocate)
		&& (m_prevPathMotionSub != static_cast<USHORT>(ClientCommand::PathSub::Reciprocate));
	const bool firstSteppingOffset =
		(sub == ClientCommand::PathSub::SteppingOffsetMove)
		&& (m_prevPathMotionSub != static_cast<USHORT>(ClientCommand::PathSub::SteppingOffsetMove));

	const PathParameter& pp = m_ClientToServer.PathCmd;
	const bool updateRise = pp.nUpdate && !m_prevPathNUpdate;

	// === Setup phase (first-command or nUpdate rising edge) ===
	if (sub == ClientCommand::PathSub::TrapezoidalProfile && (firstTrapezoidal || updateRise))
	{
		double tf = pp.nTotalTime;
		double h = pp.nStepSize;
		int len = humanoid::motion::ComputeStepCount(tf, h);
		if (len <= 0)
		{
			m_trajValid = false;
		}
		else
		{
			double ta = tf * kDefaultAccelRatio;
			if (ta < 0.0)
				ta = 0.0;
			if (ta > tf * 0.5)
				ta = tf * 0.5;
			m_trajX0 = static_cast<double>(m_MotorStArea.Data.nActualPosition);
			m_trajXf = static_cast<double>(pp.nSetPoint);
			m_trajTf = tf;
			m_trajTa = ta;
			m_trajH = h;
			m_trajLength = len;
			m_trajStep = 0;
			m_trajIsTrapezoid = true;
			m_trajValid = true;
			m_trajPaused = false;
		}
	}
	else if (sub == ClientCommand::PathSub::QuinticPolynomial && (firstQuintic || updateRise))
	{
		double tf = pp.nTotalTime;
		double h = pp.nStepSize;
		int len = humanoid::motion::ComputeStepCount(tf, h);
		if (len <= 0)
		{
			m_trajValid = false;
		}
		else
		{
			m_trajX0 = static_cast<double>(m_MotorStArea.Data.nActualPosition);
			m_trajXf = static_cast<double>(pp.nSetPoint);
			m_trajTf = tf;
			m_trajTa = 0.0;
			m_trajH = h;
			m_trajLength = len;
			m_trajStep = 0;
			m_trajIsTrapezoid = false;
			m_trajValid = true;
			m_trajPaused = false;
		}
	}
	else if (sub == ClientCommand::PathSub::Reciprocate && (firstReciprocate || updateRise))
	{
		const LONG a = m_MotorStArea.Data.nActualPosition;
		const LONG b = pp.nSetPoint;
		double tf = pp.nTotalTime;
		double h = pp.nStepSize;
		int len = humanoid::motion::ComputeStepCount(tf, h);
		if (a == b || len <= 0)
		{
			m_recipValid = false;
		}
		else
		{
			m_recipPosStart = a;
			m_recipPosTarget = b;
			m_recipLegLength = len;
			m_recipTf = tf;
			m_recipH = h;
			m_recipTa = 0.0;
			m_recipUseTrapezoid = false;
			m_recipForward = true;
			m_recipLegStep = 0;
			m_recipValid = true;
		}
	}
	else if (sub == ClientCommand::PathSub::SteppingOffsetMove && (firstSteppingOffset || updateRise))
	{
		const LONG ap = m_MotorStArea.Data.nActualPosition;
		const LONG b = pp.nSetPoint;
		const LONG dlt = b - ap;
		double tf = pp.nTotalTime;
		double h = pp.nStepSize;
		int len = humanoid::motion::ComputeStepCount(tf, h);
		if (dlt == 0 || len <= 0)
		{
			m_stepOffValid = false;
		}
		else
		{
			m_stepOffDelta = dlt;
			m_stepOffSegX0 = static_cast<double>(ap);
			m_stepOffSegXf = static_cast<double>(b);
			m_stepOffLegLen = len;
			m_stepOffTf = tf;
			m_stepOffH = h;
			m_stepOffTa = 0.0;
			m_stepOffUseTrap = false;
			m_stepOffLegStep = 0;
			m_stepOffValid = true;
		}
	}

	m_prevPathNUpdate = pp.nUpdate;

	// === Playback phase (per-sub opcode) ===
	switch (sub)
	{
	case ClientCommand::PathSub::Reciprocate:
		if (m_recipValid)
		{
			if (m_recipLegStep >= m_recipLegLength)
			{
				m_recipForward = !m_recipForward;
				m_recipLegStep = 0;
			}

			const double x0 = m_recipForward ? static_cast<double>(m_recipPosStart) : static_cast<double>(m_recipPosTarget);
			const double xf = m_recipForward ? static_cast<double>(m_recipPosTarget) : static_cast<double>(m_recipPosStart);
			const int s = m_recipLegStep;
			double t = static_cast<double>(s) * m_recipH;
			if (t > m_recipTf)
				t = m_recipTf;
			double posd;
			if (m_recipUseTrapezoid)
				posd = humanoid::motion::Trapezoidal5thAtTime(x0, xf, m_recipTf, m_recipTa, t);
			else
				posd = humanoid::motion::Single5thPosition(x0, xf, m_recipTf, t);

			const LONG p = humanoid::motion::RoundToLong(posd);
			m_MotorCmdArea.Data.nTargetPosition = p;
			m_trajLastTargetPos = p;
			m_recipLegStep = s + 1;
		}
		break;
	case ClientCommand::PathSub::SteppingOffsetMove:
		if (m_stepOffValid)
		{
			int s = m_stepOffLegStep;
			while (s >= m_stepOffLegLen && m_stepOffLegLen > 0)
			{
				m_stepOffSegX0 = m_stepOffSegXf;
				m_stepOffSegXf += static_cast<double>(m_stepOffDelta);
				s = 0;
			}

			double t = static_cast<double>(s) * m_stepOffH;
			if (t > m_stepOffTf)
				t = m_stepOffTf;
			double posd;
			if (m_stepOffUseTrap)
				posd = humanoid::motion::Trapezoidal5thAtTime(m_stepOffSegX0, m_stepOffSegXf, m_stepOffTf, m_stepOffTa, t);
			else
				posd = humanoid::motion::Single5thPosition(m_stepOffSegX0, m_stepOffSegXf, m_stepOffTf, t);

			const LONG p = humanoid::motion::RoundToLong(posd);
			m_MotorCmdArea.Data.nTargetPosition = p;
			m_trajLastTargetPos = p;
			m_stepOffLegStep = s + 1;
		}
		break;
	case ClientCommand::PathSub::Pause:
		m_trajPaused = true;
		break;
	case ClientCommand::PathSub::Resume:
		m_trajPaused = false;
		break;
	case ClientCommand::PathSub::PlayPath:
		if (m_trajValid)
		{
			if (m_trajPaused)
			{
				m_MotorCmdArea.Data.nTargetPosition = m_trajLastTargetPos;
				break;
			}

			int s = m_trajStep;
			if (s >= m_trajLength)
			{
				LONG xf = humanoid::motion::RoundToLong(m_trajXf);
				m_MotorCmdArea.Data.nTargetPosition = xf;
				m_trajLastTargetPos = xf;
				break;
			}

			double t = static_cast<double>(s) * m_trajH;
			if (t > m_trajTf)
				t = m_trajTf;
			double posd;
			if (m_trajIsTrapezoid)
				posd = humanoid::motion::Trapezoidal5thAtTime(m_trajX0, m_trajXf, m_trajTf, m_trajTa, t);
			else
				posd = humanoid::motion::Single5thPosition(m_trajX0, m_trajXf, m_trajTf, t);

			LONG p = humanoid::motion::RoundToLong(posd);
			m_MotorCmdArea.Data.nTargetPosition = p;
			m_trajLastTargetPos = p;
			m_trajStep = s + 1;
		}
		break;
	case ClientCommand::PathSub::StopHoldAndResetPath:
	{
		m_stepOffValid = false;
		m_stepOffLegStep = 0;
		m_stepOffLegLen = 0;
		m_stepOffDelta = 0;
		m_recipValid = false;
		m_recipLegStep = 0;
		m_recipLegLength = 0;
		m_trajValid = false;
		m_trajPaused = false;
		m_trajStep = 0;
		m_trajLength = 0;
		m_trajX0 = 0.0;
		m_trajXf = 0.0;
		m_trajTf = 0.0;
		m_trajTa = 0.0;
		m_trajH = 0.0;
		m_trajIsTrapezoid = false;

		const LONG ap = m_MotorStArea.Data.nActualPosition;
		m_MotorCmdArea.Data.nTargetPosition = ap;
		m_trajLastTargetPos = ap;
		// CiA 402: hold at the current position (switch-on).
		m_MotorCmdArea.Data.nControlWord = humanoid::cia402::kControlSwitchOn;
		break;
	}
	default:
		break;
	}

	m_prevPathMotionSub = subRaw;
}

///////////////////////////////////////////////////////////////////////////////
// Dispatches ModuleClientToServer.MainCmd / .SubCmd onto the single motor
// command area. Forwards Main::PathMotion to ApplyPathMotion(); handles
// ControlDrive (CiA 402 enable / quit / fault-reset stepping), SetOperationMode
// (CSP / CSV / CST) and JogModeMove (CSV velocity jog) inline. CiA 402 numeric
// constants come from humanoid::cia402::*.
void CModule::ApplyMainCmdMotorOutputs()
{
	const auto mainCmd = static_cast<ClientCommand::Main>(m_ClientToServer.MainCmd);
	const USHORT subRaw = m_ClientToServer.SubCmd;

	MotorCmd& cmd = m_MotorCmdArea.Data;
	const MotorSt& st = m_MotorStArea.Data;

	// Re-assert the last commanded operation mode every cycle, before
	// dispatching the current command, so the mode (MotorCmd.nModeOfOperation,
	// CoE 0x6060) stays latched across MainCmds: after SetOperationMode(CSV) the
	// mode survives a following ControlDrive (Enable) instead of reverting to
	// the drive default. -1 means no mode has been commanded yet.
	if (m_commandedMode >= 0)
		cmd.nModeOfOperation = static_cast<char>(m_commandedMode);

	if (mainCmd == ClientCommand::Main::PathMotion)
	{
		ApplyPathMotion();
		return;
	}

	// Any non-PathMotion command resets the "previous path sub" tracker so the
	// next entry into PathMotion is treated as a fresh first command.
	m_prevPathMotionSub = 0;

	if (mainCmd == ClientCommand::Main::SetOperationMode)
	{
		const auto sub = static_cast<ClientCommand::ModeSub>(subRaw);
		SHORT mode;
		switch (sub)
		{
		case ClientCommand::ModeSub::Csp:
			mode = humanoid::cia402::kModeCsp;
			break;
		case ClientCommand::ModeSub::Csv:
			mode = humanoid::cia402::kModeCsv;
			break;
		case ClientCommand::ModeSub::Cst:
			mode = humanoid::cia402::kModeCst;
			break;
		default:
			return;
		}

		// Latch the requested mode (re-asserted every cycle, see above) and
		// apply it immediately this cycle too.
		m_commandedMode = mode;
		cmd.nModeOfOperation = static_cast<char>(mode);
		return;
	}

	if (mainCmd == ClientCommand::Main::JogModeMove)
	{
		// Jog runs in CSV (cyclic synchronous velocity): while the command is
		// held, TargetVelocity is driven to +/- JogCmd.nJogTick. Ignored unless
		// the drive reports CSV mode of operation. Stop sets velocity to 0.
		const LONG jogVelocity = static_cast<LONG>(m_ClientToServer.JogCmd.nJogTick);
		const auto sub = static_cast<ClientCommand::JogSub>(subRaw);

		if (st.nModeOfOperationDisp != humanoid::cia402::kModeCsv)
			return;

		switch (sub)
		{
		case ClientCommand::JogSub::Positive:
			cmd.nTargetVelocity = (jogVelocity > 0) ? jogVelocity : 0;
			break;
		case ClientCommand::JogSub::Negative:
			cmd.nTargetVelocity = (jogVelocity > 0) ? -jogVelocity : 0;
			break;
		case ClientCommand::JogSub::Stop:
			cmd.nTargetVelocity = 0;
			break;
		default:
			break;
		}

		return;
	}

	if (mainCmd != ClientCommand::Main::ControlDrive)
		return;

	const auto sub = static_cast<ClientCommand::DriveSub>(subRaw);

	switch (sub)
	{
	case ClientCommand::DriveSub::EnableSequence:
	{
		// Enable sequence 6 -> 7 -> 15 from status; hold CSP target at actual
		// position to avoid a jump on enable. Skip while a fault flag is latched.
		if ((st.nStatusWord & humanoid::cia402::kStatusFaultBit) != 0)
			break;

		cmd.nTargetPosition = st.nActualPosition;

		const std::uint16_t sb = humanoid::cia402::StateBits(st.nStatusWord);
		if (sb == 0x0027U)
			cmd.nControlWord = humanoid::cia402::kControlEnableOperation;
		else if (sb == 0x0023U)
			cmd.nControlWord = humanoid::cia402::kControlEnableOperation;
		else if (sb == 0x0021U)
			cmd.nControlWord = humanoid::cia402::kControlSwitchOn;
		else
			cmd.nControlWord = humanoid::cia402::kControlShutdown;
		break;
	}
	case ClientCommand::DriveSub::QuitStep:
	{
		// Quit step: walk back from EnableOperation toward "not enabled" one
		// CiA 402 transition per cycle.
		const std::uint16_t sb = humanoid::cia402::StateBits(st.nStatusWord);
		if (sb == 0x0027U)
			cmd.nControlWord = humanoid::cia402::kControlSwitchOn;
		else if (sb == 0x0023U)
			cmd.nControlWord = humanoid::cia402::kControlShutdown;
		else if (sb == 0x0021U)
			cmd.nControlWord = humanoid::cia402::kControlShutdown;
		break;
	}
	case ClientCommand::DriveSub::FaultReset:
		// Only assert the fault-reset bit while an error code is latched.
		if (st.nErrorCode == 0)
			break;
		cmd.nControlWord = static_cast<USHORT>(cmd.nControlWord | humanoid::cia402::kControlFaultReset);
		break;
	default:
		break;
	}
}

///////////////////////////////////////////////////////////////////////////////
void CModule::AdsReadWriteInd
(
	AmsAddr& rAddr, 
	ULONG invokeId, 
	ULONG indexGroup,
	ULONG indexOffset, 
	ULONG cbReadLength, 
	ULONG cbWriteLength, 
	PVOID pData 
)
{
	m_Trace.Log(tlVerbose, FENTERA_STRV("oid=0x%08x, invokeId=%d, indexGroup=0x%08x, indexOffset=0x%08x, cbReadLength=%d, cbWriteLength=%d, pData=0x%p",
		m_objId.value, invokeId, indexGroup, indexOffset, cbReadLength, cbWriteLength, pData));

	switch(indexGroup)
	{
	case ModuleIndexGroup1:
		switch(indexOffset)
		{

		case ModuleIndexOffset1:
			m_Trace.Log(tlInfo, FNAMEA_STRV("oid=0x%08x indexGroup=0x%08x, indexOffset=0x%08x",
				m_objId.value, indexGroup, indexOffset));

			// TODO: add custom code here

			AdsReadWriteRes(rAddr, invokeId, ADSERR_NOERR, 0, NULL); 
			break;

		case ModuleIndexOffset2:
			m_Trace.Log(tlInfo, FNAMEA_STRV("oid=0x%08x indexGroup=0x%08x, indexOffset=0x%08x",
				m_objId.value, indexGroup, indexOffset));

			// TODO: add custom code here

			AdsReadWriteRes(rAddr, invokeId, ADSERR_NOERR, 0, NULL); 
			break;
		}
		break;
	case ModuleIndexGroup2:
		switch(indexOffset)
		{

		case ModuleIndexOffset1:
			m_Trace.Log(tlInfo, FNAMEA_STRV("oid=0x%08x indexGroup=0x%08x, indexOffset=0x%08x",
				m_objId.value, indexGroup, indexOffset));

			// TODO: add custom code here

			AdsReadWriteRes(rAddr, invokeId, ADSERR_NOERR, 0, NULL); 
			break;

		case ModuleIndexOffset2:
			m_Trace.Log(tlInfo, FNAMEA_STRV("oid=0x%08x indexGroup=0x%08x, indexOffset=0x%08x",
				m_objId.value, indexGroup, indexOffset));

			// TODO: add custom code here

			AdsReadWriteRes(rAddr, invokeId, ADSERR_NOERR, 0, NULL); 
			break;
		}
		break;
	default:
		__super::AdsReadWriteInd(rAddr, invokeId, indexGroup, indexOffset, cbReadLength, cbWriteLength, pData); 
		break;
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STR());
}


void CModule::SubmitAdsReadReq()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	// m_ContextAdsPort contains the ADS port number of the task associated with context 1
	// amsAddr refers to the ADS port of this task 
	AmsAddr amsAddr(this->AmsGetNetId(), m_ContextAdsPort);

	// Request the value of a parameter from a TwinCAT module instance
	// via the task ADS port.
	// The object id of the instance is passed as index group and
	// the parameter id is passed as index offset.
	// The result is delivered by a call to AdsReadCon and can 
	// be identified by the invoke id. 
	int nRes = 
		AdsReadReq
		(
			amsAddr, 
			invokeIdReadByOidAndPid, 
			m_objId.value, 
			PID_ModuleCounter,
			sizeof(m_ReadByOidAndPid)
		);
	if (nRes != ADSERR_NOERR)
	{
		m_Trace.Log(tlError, FNAMEA_STRV("AdsReadReq failed with error=0x%08x(%s)", nRes, AdsGetErrorText(nRes)));
	}
	else
	{
		m_Trace.Log(tlInfo, FNAMEA_STRV("AdsReadReq by oid=0x%08x and pid=0x%08x", m_objId.value, PID_ModuleAdsPort));
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STR());
}

///////////////////////////////////////////////////////////////////////////////
void CModule::AdsReadCon
(
	AmsAddr& rAddr,
	ULONG invokeId,
	ULONG nResult,
	ULONG cbLength,
	PVOID pData
)
{
	m_Trace.Log(tlVerbose, FENTERA_STRV("oid=0x%08x, invokeId=%d, nResult=0x%08x, cbLength=%d, pData=0x%p",
		m_objId.value, invokeId, nResult, cbLength, pData));

	if (invokeId == invokeIdReadByOidAndPid)
	{
		if (nResult != ADSERR_NOERR)
		{
			m_Trace.Log(tlWarning, FNAMEA_STRV("ReadByOidAndPid failed with error=0x%x(%s)",
				nResult, AdsGetErrorText(nResult)));
		}
		else if (cbLength == sizeof(m_ReadByOidAndPid))
		{
			m_ReadByOidAndPid = *static_cast<PULONG>(pData); 
			m_Trace.Log(tlInfo, FNAMEA_STRV("m_ReadByOidAndPid=0x%x", m_ReadByOidAndPid));
		}
	}
	else
	{
		__super::AdsReadWriteCon( rAddr, invokeId, nResult, cbLength, pData );
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STR());
}

