///////////////////////////////////////////////////////////////////////////////
// Module.h
#pragma once

#include "ControllerInterfaces.h"
#include "AdsR0.h"

// parameter ids for TwinCAT module Module with disabled code generation
// could be moved to ControllerServices.h
const PTCID PID_ModuleAdsPort        = 0x00000002;

/// Values stored in ModuleClientToServer.MainCmd / .SubCmd (USHORT in PLC).
/// Numeric values are kept byte-identical to TcUpperBodyControlMini /
/// TcLowerBodyControl so a single PLC / ADS-client vocabulary drives every
/// controller in the solution. This project controls a SINGLE motor, so the
/// data areas are scalar (no [i] arrays) but the command vocabulary is shared.
namespace ClientCommand
{
	enum class Main : USHORT
	{
		ControlDrive = 1,
		SetOperationMode = 2,
		PathMotion = 3,
		JogModeMove = 4,
	};

	/// SubCmd when Main == ControlDrive
	enum class DriveSub : USHORT
	{
		EnableSequence = 1,
		QuitStep = 2,
		FaultReset = 3,
	};

	/// SubCmd when Main == SetOperationMode (CiA 402 cyclic modes)
	enum class ModeSub : USHORT
	{
		Csp = 1,
		Csv = 2,
		Cst = 3,
	};

	/// SubCmd when Main == PathMotion. Dispatched by CModule::ApplyPathMotion().
	/// NOTE: this module's generated PathParameter has no nAccTime and no
	/// nProfileMode field, so the trapezoidal acceleration time uses a fixed
	/// default ratio and the reciprocate / stepping-offset profiles always use
	/// the quintic blend (see Module.cpp).
	enum class PathSub : USHORT
	{
		TrapezoidalProfile = 1,
		QuinticPolynomial = 2,
		PlayPath = 3,
		Reciprocate = 4,
		SteppingOffsetMove = 5,
		StopHoldAndResetPath = 6,
		Pause = 7,
		Resume = 8,
	};

	/// SubCmd when Main == JogModeMove. Jog runs in CSV (cyclic synchronous
	/// velocity); ignored unless the drive reports CSV mode of operation.
	enum class JogSub : USHORT
	{
		Positive = 1,
		Negative = 2,
		Stop = 3,
	};
}

class CModule 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
	, public CAdsR0FifoPort
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModule();
	virtual	~CModule();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

	// CAds
	virtual	void	AdsReadWriteInd
	(
		AmsAddr& rAddr, 
		ULONG invokeId, 
		ULONG indexGroup,
		ULONG indexOffset, 
		ULONG cbReadLength, 
		ULONG cbWriteLength, 
		PVOID pData 
	);

	virtual void AdsReadCon
	(
		AmsAddr& rAddr, 
		ULONG invokeId, 
		ULONG result, 
		ULONG cbLength, 
		PVOID pData
	);

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Cycle dispatch from ModuleClientToServer.MainCmd / .SubCmd for the single
	// controlled motor. Forwards Main::PathMotion to ApplyPathMotion(); handles
	// ControlDrive (CiA 402 enable / quit / fault-reset stepping),
	// SetOperationMode (CSP / CSV / CST) and JogModeMove (CSV velocity jog)
	// inline. Generated field names for this module:
	//   command mode field      = MotorCmd.nModeOfOperation   (CoE 0x6060)
	//   command velocity field  = MotorCmd.nTargetVelocity
	//   feedback mode field     = MotorSt.nModeOfOperationDisp (CoE 0x6061)
	//   path target field       = PathParameter.nSetPoint
	//   jog id field            = JogParameter.nJogIP
	void ApplyMainCmdMotorOutputs();

	// Path-motion sub-dispatch (Main::PathMotion) for the single motor. Analytic
	// trajectory state (one-shot trapezoidal / quintic, reciprocate, stepping
	// offset) plus playback opcodes (PlayPath, Pause, Resume, StopHoldAndReset).
	void ApplyPathMotion();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	WORD m_DefaultAdsPort;
	WORD m_ContextAdsPort;
	ULONG m_Counter;
	ModuleMotorStArea m_MotorStArea;
	ModuleMotorCmdArea m_MotorCmdArea;
	ModuleServerToClient m_ServerToClient;
	ModuleClientToServer m_ClientToServer;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	// Path motion state (MainCmd == PathMotion) for the single motor; analytic
	// playback, no stored path buffer.
	LONG m_trajStep;
	int m_trajLength;
	double m_trajX0;
	double m_trajXf;
	double m_trajTf;
	double m_trajTa;
	double m_trajH;
	bool m_trajIsTrapezoid;
	bool m_trajValid;
	bool m_trajPaused;
	bool m_prevPathNUpdate;
	LONG m_trajLastTargetPos;
	USHORT m_prevPathMotionSub;

	// Reciprocate (PathSub::Reciprocate): A <-> B
	bool m_recipValid;
	bool m_recipForward;
	LONG m_recipPosStart;
	LONG m_recipPosTarget;
	int m_recipLegStep;
	int m_recipLegLength;
	double m_recipTf;
	double m_recipH;
	double m_recipTa;
	bool m_recipUseTrapezoid;

	// SteppingOffsetMove (PathSub::SteppingOffsetMove): segment to segXf, then
	// segXf += delta each completion.
	bool m_stepOffValid;
	LONG m_stepOffDelta;
	double m_stepOffSegX0;
	double m_stepOffSegXf;
	int m_stepOffLegStep;
	int m_stepOffLegLen;
	double m_stepOffTf;
	double m_stepOffH;
	double m_stepOffTa;
	bool m_stepOffUseTrap;

	// Last operation mode requested through Main::SetOperationMode (CiA 402:
	// 8 = CSP, 9 = CSV, 10 = CST). Re-asserted into MotorCmd.nModeOfOperation
	// (CoE 0x6060) every cycle so the commanded mode survives across subsequent
	// MainCmds such as ControlDrive. -1 = no mode commanded yet (left untouched).
	SHORT m_commandedMode;

	void SubmitAdsReadReq();
	enum 
	{
		invokeIdReadByOidAndPid = 1
	};
	ULONG  m_ReadByOidAndPid;
};
