///////////////////////////////////////////////////////////////////////////////
// ControllerServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Controller = 0x3F000000;
#define SRVNAME_CONTROLLER "Controller"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ControllerCModule = {0xcaf14bc6,0x8c3e,0x4497,{0xb9,0xc7,0xc5,0x7c,0x83,0xc0,0x30,0xc7}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleMotorStArea 0
#define ADI_ModuleMotorCmdArea 1
#define ADI_ModuleServerToClient 3
#define ADI_ModuleClientToServer 4
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleDefaultAdsPort = 0x00000001;
const PTCID PID_ModuleCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_284DF5A2_1A3B_46FC_A5F2_6D96C5A94F64_INCLUDED_)
#define _TC_TYPE_284DF5A2_1A3B_46FC_A5F2_6D96C5A94F64_INCLUDED_
#pragma pack(push,1)
typedef struct _MotorSt
{
	USHORT nStatusWord;
	LONG nActualPosition;
	LONG nActualVelocity;
	SHORT nActualTorque;
	USHORT nErrorCode;
	char nModeOfOperationDisp;
} MotorSt, *PMotorSt;
#pragma pack(pop)
const GUID GUID_MotorSt = {0x284DF5A2, 0x1A3B, 0x46FC, {0xA5, 0xF2, 0x6D, 0x96, 0xC5, 0xA9, 0x4F, 0x64}};
#endif // !defined(_TC_TYPE_284DF5A2_1A3B_46FC_A5F2_6D96C5A94F64_INCLUDED_)

#if !defined(_TC_TYPE_773B787B_A75B_4727_8157_62F88A9DC62B_INCLUDED_)
#define _TC_TYPE_773B787B_A75B_4727_8157_62F88A9DC62B_INCLUDED_
#pragma pack(push,1)
typedef struct _ModorCmd
{
	USHORT nControlWord;
	LONG nTargetPosition;
	LONG nTargetVelocity;
	SHORT nTargetTorque;
	USHORT nMaxTorque;
	char nModeOfOperation;
} ModorCmd, *PModorCmd;
#pragma pack(pop)
const GUID GUID_ModorCmd = {0x773B787B, 0xA75B, 0x4727, {0x81, 0x57, 0x62, 0xF8, 0x8A, 0x9D, 0xC6, 0x2B}};
#endif // !defined(_TC_TYPE_773B787B_A75B_4727_8157_62F88A9DC62B_INCLUDED_)

#if !defined(_TC_TYPE_F437E7C1_944C_44C6_A869_EB7CC0408295_INCLUDED_)
#define _TC_TYPE_F437E7C1_944C_44C6_A869_EB7CC0408295_INCLUDED_
#pragma pack(push,1)
typedef struct _PathParameter
{
	double nTotalTime;
	double nStepSize;
	bool nUpdate;
	LONG nSetPosition;
} PathParameter, *PPathParameter;
#pragma pack(pop)
const GUID GUID_PathParameter = {0xF437E7C1, 0x944C, 0x44C6, {0xA8, 0x69, 0xEB, 0x7C, 0xC0, 0x40, 0x82, 0x95}};
#endif // !defined(_TC_TYPE_F437E7C1_944C_44C6_A869_EB7CC0408295_INCLUDED_)

#if !defined(_TC_TYPE_9E65A044_C2A1_4029_8A62_987F2E4840E5_INCLUDED_)
#define _TC_TYPE_9E65A044_C2A1_4029_8A62_987F2E4840E5_INCLUDED_
typedef struct _JogParameter
{
	USHORT nJogID;
	USHORT nJogTick;
} JogParameter, *PJogParameter;
const GUID GUID_JogParameter = {0x9E65A044, 0xC2A1, 0x4029, {0x8A, 0x62, 0x98, 0x7F, 0x2E, 0x48, 0x40, 0xE5}};
#endif // !defined(_TC_TYPE_9E65A044_C2A1_4029_8A62_987F2E4840E5_INCLUDED_)

#pragma pack(push,1)
typedef struct _ModuleMotorStArea
{
	MotorSt Data[7];
} ModuleMotorStArea, *PModuleMotorStArea;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleMotorCmdArea
{
	ModorCmd Data[7];
} ModuleMotorCmdArea, *PModuleMotorCmdArea;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleServerToClient
{
	MotorSt DataMotorSt[7];
	ModorCmd DataMotorCmd[7];
} ModuleServerToClient, *PModuleServerToClient;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _ModuleClientToServer
{
	USHORT MainCmd;
	USHORT SubCmd;
	PathParameter PathCmd[7];
	JogParameter JogCmd;
} ModuleClientToServer, *PModuleClientToServer;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
