///////////////////////////////////////////////////////////////////////////////
// Module.h
#pragma once

#include "ControllerInterfaces.h"
#include "AdsR0.h"

// parameter ids for TwinCAT module Module with disabled code generation
// could be moved to ControllerServices.h
const PTCID PID_ModuleAdsPort        = 0x00000002;

// Active motor count for this "Mini" upper-body module. Taken from the
// generated data-area dimension (ModuleMotorStArea.Data[7] in
// ControllerServices.h). A static_assert in Module.cpp ties this constant
// back to sizeof(m_MotorStArea.Data) so the two can never drift.
static constexpr int kMotorCount = 7;

/// Values stored in ModuleClientToServer.MainCmd / .SubCmd (USHORT in PLC).
/// Numeric values are kept byte-identical to TcLowerBodyControl /
/// TcUpperBodyController so a single PLC / ADS-client vocabulary drives every
/// controller in the solution.
namespace ClientCommand
{
	enum class Main : USHORT
	{
		ControlDrive = 1,
		SetOperationMode = 2,
		PathMotion = 3,
		JogModeMove = 4,
	};

	/// SubCmd when Main == ControlDrive
	enum class DriveSub : USHORT
	{
		EnableSequence = 1,
		QuitStep = 2,
		FaultReset = 3,
	};

	/// SubCmd when Main == SetOperationMode (CiA 402 cyclic modes)
	enum class ModeSub : USHORT
	{
		Csp = 1,
		Csv = 2,
		Cst = 3,
	};

	/// SubCmd when Main == PathMotion. Dispatched by CModule::ApplyPathMotion().
	/// NOTE: this Mini module's generated PathParameter has no nAccTime and no
	/// nProfileMode field, so the trapezoidal acceleration time uses a fixed
	/// default ratio and the reciprocate / stepping-offset profiles always use
	/// the quintic blend (see Module.cpp).
	enum class PathSub : USHORT
	{
		TrapezoidalProfile = 1,
		QuinticPolynomial = 2,
		PlayPath = 3,
		Reciprocate = 4,
		SteppingOffsetMove = 5,
		StopHoldAndResetPath = 6,
		Pause = 7,
		Resume = 8,
	};

	/// SubCmd when Main == JogModeMove. Jog runs in CSV (cyclic synchronous
	/// velocity); ignored unless the drive reports CSV mode of operation.
	enum class JogSub : USHORT
	{
		Positive = 1,
		Negative = 2,
		Stop = 3,
	};
}

class CModule 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
	, public CAdsR0FifoPort
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CModule();
	virtual	~CModule();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

	// CAds
	virtual	void	AdsReadWriteInd
	(
		AmsAddr& rAddr, 
		ULONG invokeId, 
		ULONG indexGroup,
		ULONG indexOffset, 
		ULONG cbReadLength, 
		ULONG cbWriteLength, 
		PVOID pData 
	);

	virtual void AdsReadCon
	(
		AmsAddr& rAddr, 
		ULONG invokeId, 
		ULONG result, 
		ULONG cbLength, 
		PVOID pData
	);

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Cycle dispatch from ModuleClientToServer.MainCmd / .SubCmd. Loops only
	// over kMotorCount (7). Forwards Main::PathMotion to ApplyPathMotion();
	// handles ControlDrive (CiA 402 enable / quit / fault-reset stepping),
	// SetOperationMode (CSP / CSV / CST) and JogModeMove (CSV velocity jog)
	// inline. Ported from TcLowerBodyControl and adapted to this module's
	// generated field names (command mode field is nModeOfOperation /
	// CoE 0x6060, feedback mode field is nModeOfOperationDisp / CoE 0x6061,
	// command velocity field is nTargetVelocity, jog id field is nJogID) and
	// to the absence of an nWcState process-link flag.
	void ApplyMainCmdMotorOutputs();

	// Path-motion sub-dispatch (Main::PathMotion). Per-motor trajectory state
	// machines (one-shot trapezoidal / quintic, reciprocate, stepping offset)
	// plus the playback opcodes (PlayPath, Pause, Resume, StopHoldAndResetPath).
	void ApplyPathMotion();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	WORD m_DefaultAdsPort;
	WORD m_ContextAdsPort;
	ULONG m_Counter;
	ModuleMotorStArea m_MotorStArea;
	ModuleMotorCmdArea m_MotorCmdArea;
	ModuleServerToClient m_ServerToClient;
	ModuleClientToServer m_ClientToServer;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>

	// Path motion state (MainCmd == PathMotion); analytic playback, no stored
	// path buffer. All arrays are sized by kMotorCount (7).
	LONG m_trajStep[kMotorCount];
	int m_trajLength[kMotorCount];
	double m_trajX0[kMotorCount];
	double m_trajXf[kMotorCount];
	double m_trajTf[kMotorCount];
	double m_trajTa[kMotorCount];
	double m_trajH[kMotorCount];
	bool m_trajIsTrapezoid[kMotorCount];
	bool m_trajValid[kMotorCount];
	bool m_trajPaused[kMotorCount];
	bool m_prevPathNUpdate[kMotorCount];
	LONG m_trajLastTargetPos[kMotorCount];
	USHORT m_prevPathMotionSub;

	// Reciprocate (PathSub::Reciprocate): A <-> B per axis
	bool m_recipValid[kMotorCount];
	bool m_recipForward[kMotorCount];
	LONG m_recipPosStart[kMotorCount];
	LONG m_recipPosTarget[kMotorCount];
	int m_recipLegStep[kMotorCount];
	int m_recipLegLength[kMotorCount];
	double m_recipTf[kMotorCount];
	double m_recipH[kMotorCount];
	double m_recipTa[kMotorCount];
	bool m_recipUseTrapezoid[kMotorCount];

	// SteppingOffsetMove (PathSub::SteppingOffsetMove): segment to segXf,
	// then segXf += delta each completion.
	bool m_stepOffValid[kMotorCount];
	LONG m_stepOffDelta[kMotorCount];
	double m_stepOffSegX0[kMotorCount];
	double m_stepOffSegXf[kMotorCount];
	int m_stepOffLegStep[kMotorCount];
	int m_stepOffLegLen[kMotorCount];
	double m_stepOffTf[kMotorCount];
	double m_stepOffH[kMotorCount];
	double m_stepOffTa[kMotorCount];
	bool m_stepOffUseTrap[kMotorCount];

	// Last operation mode requested through Main::SetOperationMode (CiA 402:
	// 8 = CSP, 9 = CSV, 10 = CST). It is re-asserted into the command mode
	// field (ModorCmd.nModeOfOperation, CoE 0x6060) of every motor on every
	// cycle, so a commanded mode survives across subsequent MainCmds such as
	// ControlDrive. Without this, enabling a drive (ControlDrive) leaves the
	// mode field untouched and the drive can fall back to its default (CSP=8),
	// which is exactly the "set CSV(9), then Enable -> reverts to 8" symptom.
	// Value -1 means "no mode commanded yet" -> the field is left untouched.
	SHORT m_commandedMode;

	void SubmitAdsReadReq();
	enum 
	{
		invokeIdReadByOidAndPid = 1
	};
	ULONG  m_ReadByOidAndPid;
};
