///////////////////////////////////////////////////////////////////////////////
// Module.cpp
#include "TcPch.h"
#pragma hdrstop

#include <cstring>

#include "Module.h"
#include "ModuleAds.h"
#include "ControllerVersion.h"

// Shared header-only libraries. Pure C++; independent from TwinCAT/TcCOM/
// TMC/ADS/EtherCAT headers. Resolved via this project's
// AdditionalIncludeDirectories entries (..\..\..\common\humanoid_common\include
// and ..\..\..\common\humanoid_motion\include).
//
// IMPORTANT: this Mini project's Controller.vcxproj does NOT yet carry those
// two include directories for the build platform (Release|TwinCAT OS (x64-E)).
// They must be added there before this file compiles. See the handover notes.
#include "humanoid_common/cia402.h"
#include "humanoid_motion/trajectory_profile.h"

// Compile-time verification that the shared headers are reachable and that the
// motor-count constant matches the generated data area dimension.
static_assert(sizeof(((ModuleMotorStArea*)0)->Data) / sizeof(((ModuleMotorStArea*)0)->Data[0]) == kMotorCount,
              "kMotorCount must match ModuleMotorStArea.Data element count");
static_assert(humanoid::cia402::kModeCsp == 8,
              "humanoid::cia402: CSP mode value must be 8");
static_assert(humanoid::cia402::kModeCsv == 9,
              "humanoid::cia402: CSV mode value must be 9");

namespace {

// Trapezoidal acceleration time as a fraction of total time. The Mini
// PathParameter has no nAccTime field, so the trapezoidal profile derives the
// blend time from the requested total time. Clamped to [0, tf*0.5] downstream.
constexpr double kDefaultAccelRatio = 0.3;

}  // namespace

///////////////////////////////////////////////////////////////////////////////
// CModule
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CModule
BEGIN_INTERFACE_MAP(CModule)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CModule, VID_Controller, CID_ControllerCModule)
IMPLEMENT_ITCOMOBJECT(CModule)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CModule)
IMPLEMENT_ITCADI(CModule)
IMPLEMENT_ITCWATCHSOURCE(CModule)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CModule 
BEGIN_SETOBJPARA_MAP(CModule)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_ModuleDefaultAdsPort, m_DefaultAdsPort)
	SETOBJPARA_VALUE(PID_Ctx_AdsPort, m_ContextAdsPort)
	SETOBJPARA_VALUE(PID_ModuleCounter, m_Counter)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CModule 
BEGIN_GETOBJPARA_MAP(CModule)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_ModuleDefaultAdsPort, m_DefaultAdsPort)
	GETOBJPARA_VALUE(PID_Ctx_AdsPort, m_ContextAdsPort)
	GETOBJPARA_VALUE(PID_ModuleCounter, m_Counter)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
	GETOBJPARA_TYPE_CODE(PID_ModuleAdsPort, WORD, *p = AmsGetPort())
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CModule
BEGIN_OBJPARAWATCH_MAP(CModule)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
	OBJPARAWATCH_VALUE(PID_ModuleCounter, m_Counter)
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CModule
BEGIN_OBJDATAAREA_MAP(CModule)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_ModuleMotorStArea, m_MotorStArea)
	OBJDATAAREA_VALUE(ADI_ModuleMotorCmdArea, m_MotorCmdArea)
	OBJDATAAREA_VALUE(ADI_ModuleServerToClient, m_ServerToClient)
	OBJDATAAREA_VALUE(ADI_ModuleClientToServer, m_ClientToServer)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CModule::CModule()
	: m_Trace(m_TraceLevelMax, m_spSrv)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	m_DefaultAdsPort = 0;
	m_ContextAdsPort = 0;
	m_Counter = 0;
	memset(&m_MotorStArea, 0, sizeof(m_MotorStArea));
	memset(&m_MotorCmdArea, 0, sizeof(m_MotorCmdArea));
	memset(&m_ServerToClient, 0, sizeof(m_ServerToClient));
	memset(&m_ClientToServer, 0, sizeof(m_ClientToServer));
///</AutoGeneratedContent>

	// Explicit initialisation of all path-motion state. These members are not
	// covered by any of the auto-generated memset blocks above, so each new
	// CModule instance must clear them deterministically before the first
	// CycleUpdate. Loop bound is kMotorCount (7).
	for (int i = 0; i < kMotorCount; ++i)
	{
		m_trajStep[i] = 0;
		m_trajLength[i] = 0;
		m_trajX0[i] = 0.0;
		m_trajXf[i] = 0.0;
		m_trajTf[i] = 0.0;
		m_trajTa[i] = 0.0;
		m_trajH[i] = 0.0;
		m_trajIsTrapezoid[i] = false;
		m_trajValid[i] = false;
		m_trajPaused[i] = false;
		m_prevPathNUpdate[i] = false;
		m_trajLastTargetPos[i] = 0;

		m_recipValid[i] = false;
		m_recipForward[i] = false;
		m_recipPosStart[i] = 0;
		m_recipPosTarget[i] = 0;
		m_recipLegStep[i] = 0;
		m_recipLegLength[i] = 0;
		m_recipTf[i] = 0.0;
		m_recipH[i] = 0.0;
		m_recipTa[i] = 0.0;
		m_recipUseTrapezoid[i] = false;

		m_stepOffValid[i] = false;
		m_stepOffDelta[i] = 0;
		m_stepOffSegX0[i] = 0.0;
		m_stepOffSegXf[i] = 0.0;
		m_stepOffLegStep[i] = 0;
		m_stepOffLegLen[i] = 0;
		m_stepOffTf[i] = 0.0;
		m_stepOffH[i] = 0.0;
		m_stepOffTa[i] = 0.0;
		m_stepOffUseTrap[i] = false;
	}
	m_prevPathMotionSub = 0;
	m_commandedMode = -1;
}

///////////////////////////////////////////////////////////////////////////////
CModule::~CModule() 
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CModule)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CModule::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	hr = SUCCEEDED(hr) ? InitAmsPort(m_spSrv, m_DefaultAdsPort) : hr;

	// cleanup on failure
	if (FAILED(hr))
	{
		ShutdownAmsPort();
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CModule::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization


	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before this method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CModule::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CModule::SetObjStateSP()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	HRESULT hr = S_OK;
	ShutdownAmsPort();

	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CModule::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// handle pending ADS indications and confirmations
	CheckOrders();

	// Mirror the EtherCAT-driven motor state into the PLC / ADS-visible area,
	// run the active command dispatch, then publish the patched motor command
	// area. ApplyMainCmdMotorOutputs() only patches selected fields.
	memcpy(m_ServerToClient.DataMotorSt, m_MotorStArea.Data, sizeof(m_MotorStArea.Data));
	ApplyMainCmdMotorOutputs();
	memcpy(m_ServerToClient.DataMotorCmd, m_MotorCmdArea.Data, sizeof(m_MotorCmdArea.Data));

	// TODO: Submit your ADS requests 
	ULONGLONG cnt = 0;
	if (SUCCEEDED(ipTask->GetCycleCounter(&cnt)))
	{
		if (cnt%100 == 0)
		{
			SubmitAdsReadReq();
		}
	}

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CModule::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STRV("hr=0x%08x", hr));
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CModule::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
	m_Trace.Log(tlVerbose, FLEAVEA_STR());
}

///////////////////////////////////////////////////////////////////////////////
// Per-cycle dispatch for Main::PathMotion. Trajectory primitives come from
// humanoid::motion::* (header-only). All loops use kMotorCount (7).
//
// Adapted from TcLowerBodyControl: this Mini PathParameter has no nAccTime and
// no nProfileMode field, and this module's MotorSt has no nWcState process-link
// flag. Therefore: the trapezoidal acceleration time uses kDefaultAccelRatio
// (clamped to [0, tf*0.5]); reciprocate / stepping-offset always use the
// quintic blend; and the per-axis nWcState gates are dropped.
void CModule::ApplyPathMotion()
{
	const USHORT subRaw = m_ClientToServer.SubCmd;
	const auto sub = static_cast<ClientCommand::PathSub>(subRaw);

	const bool firstTrapezoidal =
		(sub == ClientCommand::PathSub::TrapezoidalProfile)
		&& (m_prevPathMotionSub != static_cast<USHORT>(ClientCommand::PathSub::TrapezoidalProfile));
	const bool firstQuintic =
		(sub == ClientCommand::PathSub::QuinticPolynomial)
		&& (m_prevPathMotionSub != static_cast<USHORT>(ClientCommand::PathSub::QuinticPolynomial));
	const bool firstReciprocate =
		(sub == ClientCommand::PathSub::Reciprocate)
		&& (m_prevPathMotionSub != static_cast<USHORT>(ClientCommand::PathSub::Reciprocate));
	const bool firstSteppingOffset =
		(sub == ClientCommand::PathSub::SteppingOffsetMove)
		&& (m_prevPathMotionSub != static_cast<USHORT>(ClientCommand::PathSub::SteppingOffsetMove));

	// === Setup phase (first-command or per-axis nUpdate rising edge) ===
	for (int i = 0; i < kMotorCount; ++i)
	{
		const PathParameter& pp = m_ClientToServer.PathCmd[i];
		const bool updateRise = pp.nUpdate && !m_prevPathNUpdate[i];

		if (sub == ClientCommand::PathSub::TrapezoidalProfile && (firstTrapezoidal || updateRise))
		{
			double tf = pp.nTotalTime;
			double h = pp.nStepSize;
			int len = humanoid::motion::ComputeStepCount(tf, h);
			if (len <= 0)
			{
				m_trajValid[i] = false;
				m_prevPathNUpdate[i] = pp.nUpdate;
				continue;
			}
			double ta = tf * kDefaultAccelRatio;
			if (ta < 0.0)
				ta = 0.0;
			if (ta > tf * 0.5)
				ta = tf * 0.5;
			m_trajX0[i] = static_cast<double>(m_MotorStArea.Data[i].nActualPosition);
			m_trajXf[i] = static_cast<double>(pp.nSetPosition);
			m_trajTf[i] = tf;
			m_trajTa[i] = ta;
			m_trajH[i] = h;
			m_trajLength[i] = len;
			m_trajStep[i] = 0;
			m_trajIsTrapezoid[i] = true;
			m_trajValid[i] = true;
			m_trajPaused[i] = false;
		}
		else if (sub == ClientCommand::PathSub::QuinticPolynomial && (firstQuintic || updateRise))
		{
			double tf = pp.nTotalTime;
			double h = pp.nStepSize;
			int len = humanoid::motion::ComputeStepCount(tf, h);
			if (len <= 0)
			{
				m_trajValid[i] = false;
				m_prevPathNUpdate[i] = pp.nUpdate;
				continue;
			}
			m_trajX0[i] = static_cast<double>(m_MotorStArea.Data[i].nActualPosition);
			m_trajXf[i] = static_cast<double>(pp.nSetPosition);
			m_trajTf[i] = tf;
			m_trajTa[i] = 0.0;
			m_trajH[i] = h;
			m_trajLength[i] = len;
			m_trajStep[i] = 0;
			m_trajIsTrapezoid[i] = false;
			m_trajValid[i] = true;
			m_trajPaused[i] = false;
		}
		else if (sub == ClientCommand::PathSub::Reciprocate && (firstReciprocate || updateRise))
		{
			const LONG a = m_MotorStArea.Data[i].nActualPosition;
			const LONG b = pp.nSetPosition;
			if (a == b)
			{
				m_recipValid[i] = false;
				m_prevPathNUpdate[i] = pp.nUpdate;
				continue;
			}
			double tf = pp.nTotalTime;
			double h = pp.nStepSize;
			int len = humanoid::motion::ComputeStepCount(tf, h);
			if (len <= 0)
			{
				m_recipValid[i] = false;
				m_prevPathNUpdate[i] = pp.nUpdate;
				continue;
			}
			m_recipPosStart[i] = a;
			m_recipPosTarget[i] = b;
			m_recipLegLength[i] = len;
			m_recipTf[i] = tf;
			m_recipH[i] = h;
			m_recipTa[i] = 0.0;
			m_recipUseTrapezoid[i] = false;
			m_recipForward[i] = true;
			m_recipLegStep[i] = 0;
			m_recipValid[i] = true;
		}
		else if (sub == ClientCommand::PathSub::SteppingOffsetMove && (firstSteppingOffset || updateRise))
		{
			const LONG ap = m_MotorStArea.Data[i].nActualPosition;
			const LONG b = pp.nSetPosition;
			const LONG dlt = b - ap;
			if (dlt == 0)
			{
				m_stepOffValid[i] = false;
				m_prevPathNUpdate[i] = pp.nUpdate;
				continue;
			}
			double tf = pp.nTotalTime;
			double h = pp.nStepSize;
			int len = humanoid::motion::ComputeStepCount(tf, h);
			if (len <= 0)
			{
				m_stepOffValid[i] = false;
				m_prevPathNUpdate[i] = pp.nUpdate;
				continue;
			}
			m_stepOffDelta[i] = dlt;
			m_stepOffSegX0[i] = static_cast<double>(ap);
			m_stepOffSegXf[i] = static_cast<double>(b);
			m_stepOffLegLen[i] = len;
			m_stepOffTf[i] = tf;
			m_stepOffH[i] = h;
			m_stepOffTa[i] = 0.0;
			m_stepOffUseTrap[i] = false;
			m_stepOffLegStep[i] = 0;
			m_stepOffValid[i] = true;
		}

		m_prevPathNUpdate[i] = pp.nUpdate;
	}

	// === Playback phase (per-sub opcode) ===
	switch (sub)
	{
	case ClientCommand::PathSub::Reciprocate:
		for (int i = 0; i < kMotorCount; ++i)
		{
			if (!m_recipValid[i])
				continue;

			if (m_recipLegStep[i] >= m_recipLegLength[i])
			{
				m_recipForward[i] = !m_recipForward[i];
				m_recipLegStep[i] = 0;
			}

			const double x0 = m_recipForward[i] ? static_cast<double>(m_recipPosStart[i]) : static_cast<double>(m_recipPosTarget[i]);
			const double xf = m_recipForward[i] ? static_cast<double>(m_recipPosTarget[i]) : static_cast<double>(m_recipPosStart[i]);
			const int s = m_recipLegStep[i];
			double t = static_cast<double>(s) * m_recipH[i];
			if (t > m_recipTf[i])
				t = m_recipTf[i];
			double posd;
			if (m_recipUseTrapezoid[i])
				posd = humanoid::motion::Trapezoidal5thAtTime(x0, xf, m_recipTf[i], m_recipTa[i], t);
			else
				posd = humanoid::motion::Single5thPosition(x0, xf, m_recipTf[i], t);

			const LONG p = humanoid::motion::RoundToLong(posd);
			m_MotorCmdArea.Data[i].nTargetPosition = p;
			m_trajLastTargetPos[i] = p;
			m_recipLegStep[i] = s + 1;
		}
		break;
	case ClientCommand::PathSub::SteppingOffsetMove:
		for (int i = 0; i < kMotorCount; ++i)
		{
			if (!m_stepOffValid[i])
				continue;

			int s = m_stepOffLegStep[i];
			while (s >= m_stepOffLegLen[i] && m_stepOffLegLen[i] > 0)
			{
				m_stepOffSegX0[i] = m_stepOffSegXf[i];
				m_stepOffSegXf[i] += static_cast<double>(m_stepOffDelta[i]);
				s = 0;
			}

			double t = static_cast<double>(s) * m_stepOffH[i];
			if (t > m_stepOffTf[i])
				t = m_stepOffTf[i];
			double posd;
			if (m_stepOffUseTrap[i])
				posd = humanoid::motion::Trapezoidal5thAtTime(m_stepOffSegX0[i], m_stepOffSegXf[i], m_stepOffTf[i], m_stepOffTa[i], t);
			else
				posd = humanoid::motion::Single5thPosition(m_stepOffSegX0[i], m_stepOffSegXf[i], m_stepOffTf[i], t);

			const LONG p = humanoid::motion::RoundToLong(posd);
			m_MotorCmdArea.Data[i].nTargetPosition = p;
			m_trajLastTargetPos[i] = p;
			m_stepOffLegStep[i] = s + 1;
		}
		break;
	case ClientCommand::PathSub::Pause:
		for (int i = 0; i < kMotorCount; ++i)
			m_trajPaused[i] = true;
		break;
	case ClientCommand::PathSub::Resume:
		for (int i = 0; i < kMotorCount; ++i)
			m_trajPaused[i] = false;
		break;
	case ClientCommand::PathSub::PlayPath:
		for (int i = 0; i < kMotorCount; ++i)
		{
			if (!m_trajValid[i])
				continue;

			if (m_trajPaused[i])
			{
				m_MotorCmdArea.Data[i].nTargetPosition = m_trajLastTargetPos[i];
				continue;
			}

			int s = m_trajStep[i];
			if (s >= m_trajLength[i])
			{
				LONG xf = humanoid::motion::RoundToLong(m_trajXf[i]);
				m_MotorCmdArea.Data[i].nTargetPosition = xf;
				m_trajLastTargetPos[i] = xf;
				continue;
			}

			double t = static_cast<double>(s) * m_trajH[i];
			if (t > m_trajTf[i])
				t = m_trajTf[i];
			double posd;
			if (m_trajIsTrapezoid[i])
				posd = humanoid::motion::Trapezoidal5thAtTime(m_trajX0[i], m_trajXf[i], m_trajTf[i], m_trajTa[i], t);
			else
				posd = humanoid::motion::Single5thPosition(m_trajX0[i], m_trajXf[i], m_trajTf[i], t);

			LONG p = humanoid::motion::RoundToLong(posd);
			m_MotorCmdArea.Data[i].nTargetPosition = p;
			m_trajLastTargetPos[i] = p;
			m_trajStep[i] = s + 1;
		}
		break;
	case ClientCommand::PathSub::StopHoldAndResetPath:
		for (int i = 0; i < kMotorCount; ++i)
		{
			m_stepOffValid[i] = false;
			m_stepOffLegStep[i] = 0;
			m_stepOffLegLen[i] = 0;
			m_stepOffDelta[i] = 0;
			m_recipValid[i] = false;
			m_recipLegStep[i] = 0;
			m_recipLegLength[i] = 0;
			m_trajValid[i] = false;
			m_trajPaused[i] = false;
			m_trajStep[i] = 0;
			m_trajLength[i] = 0;
			m_trajX0[i] = 0.0;
			m_trajXf[i] = 0.0;
			m_trajTf[i] = 0.0;
			m_trajTa[i] = 0.0;
			m_trajH[i] = 0.0;
			m_trajIsTrapezoid[i] = false;

			const LONG ap = m_MotorStArea.Data[i].nActualPosition;
			m_MotorCmdArea.Data[i].nTargetPosition = ap;
			m_trajLastTargetPos[i] = ap;
			// CiA 402: switch-on (hold); CSP follows target == actual at the
			// current position.
			m_MotorCmdArea.Data[i].nControlWord = humanoid::cia402::kControlSwitchOn;
		}
		break;
	default:
		break;
	}

	m_prevPathMotionSub = subRaw;
}

///////////////////////////////////////////////////////////////////////////////
// Dispatches ModuleClientToServer.MainCmd / .SubCmd onto the motor command
// area. Forwards Main::PathMotion to ApplyPathMotion(); handles ControlDrive
// (CiA 402 enable / quit / fault-reset stepping), SetOperationMode (CSP / CSV /
// CST) and JogModeMove (CSV velocity jog) inline. All loops are bounded by
// kMotorCount (7). CiA 402 numeric constants come from humanoid::cia402::*.
//
// Field-name note (as actually generated by this Mini TMC / linked to the
// EtherCAT drive PDOs):
//   command mode field      = ModorCmd.nModeOfOperation   (CoE 0x6060 "modes of operation")
//   command velocity field  = ModorCmd.nTargetVelocity
//   feedback mode field     = MotorSt.nModeOfOperationDisp (CoE 0x6061 "modes of operation display")
//   jog id field            = JogParameter.nJogID
void CModule::ApplyMainCmdMotorOutputs()
{
	const auto mainCmd = static_cast<ClientCommand::Main>(m_ClientToServer.MainCmd);
	const USHORT subRaw = m_ClientToServer.SubCmd;

	// Re-assert the last commanded operation mode on every cycle, for every
	// motor, before dispatching the current command. This keeps the mode
	// (ModorCmd.nModeOfOperation, CoE 0x6060) latched across MainCmds: e.g.
	// after SetOperationMode(CSV) the mode survives a following ControlDrive
	// (Enable) instead of reverting to the drive default (CSP=8). -1 means no
	// mode has been commanded yet, so the field is left untouched.
	if (m_commandedMode >= 0)
	{
		for (int i = 0; i < kMotorCount; ++i)
			m_MotorCmdArea.Data[i].nModeOfOperation = static_cast<char>(m_commandedMode);
	}

	if (mainCmd == ClientCommand::Main::PathMotion)
	{
		ApplyPathMotion();
		return;
	}

	// Any non-PathMotion command resets the "previous path sub" tracker so the
	// next entry into PathMotion is treated as a fresh first command.
	m_prevPathMotionSub = 0;

	if (mainCmd == ClientCommand::Main::SetOperationMode)
	{
		const auto sub = static_cast<ClientCommand::ModeSub>(subRaw);
		SHORT mode;
		switch (sub)
		{
		case ClientCommand::ModeSub::Csp:
			mode = humanoid::cia402::kModeCsp;
			break;
		case ClientCommand::ModeSub::Csv:
			mode = humanoid::cia402::kModeCsv;
			break;
		case ClientCommand::ModeSub::Cst:
			mode = humanoid::cia402::kModeCst;
			break;
		default:
			return;
		}

		// Latch the requested mode so it is re-asserted every cycle (see the
		// top of this function) and apply it immediately this cycle too.
		m_commandedMode = mode;
		for (int i = 0; i < kMotorCount; ++i)
			m_MotorCmdArea.Data[i].nModeOfOperation = static_cast<char>(mode);
		return;
	}

	if (mainCmd == ClientCommand::Main::JogModeMove)
	{
		// Jog command split:
		//   SubCmd                       : direction (JogSub values)
		//   ClientToServer.JogCmd.nJodID : target axis id (sic)
		//   ClientToServer.JogCmd.nJogTick : target velocity magnitude
		// Jog runs in CSV (cyclic synchronous velocity): while the command is
		// held, the selected axis TargetVelocity is driven to +/- tick. Only
		// one axis jogs at a time: every other axis is forced to 0, so switching
		// axes without an explicit Stop halts the previously jogged axis. Stop
		// sets the selected axis to 0. Per axis it is ignored unless the drive
		// reports CSV mode of operation.
		const USHORT jogId = m_ClientToServer.JogCmd.nJogID;
		const LONG jogVelocity = static_cast<LONG>(m_ClientToServer.JogCmd.nJogTick);
		const auto sub = static_cast<ClientCommand::JogSub>(subRaw);

		// Accept both 0-based [0..6] and 1-based [1..7] axis ids.
		int axis = -1;
		if (jogId < static_cast<USHORT>(kMotorCount))
			axis = static_cast<int>(jogId);
		else if (jogId >= 1U && jogId <= static_cast<USHORT>(kMotorCount))
			axis = static_cast<int>(jogId - 1U);
		if (axis < 0 || axis >= kMotorCount)
			return;

		for (int i = 0; i < kMotorCount; ++i)
		{
			ModorCmd& cmd = m_MotorCmdArea.Data[i];
			const MotorSt& st = m_MotorStArea.Data[i];

			if (st.nModeOfOperationDisp != humanoid::cia402::kModeCsv)
				continue;

			// Every axis other than the selected one is stopped.
			if (i != axis)
			{
				cmd.nTargetVelocity = 0;
				continue;
			}

			switch (sub)
			{
			case ClientCommand::JogSub::Positive:
				cmd.nTargetVelocity = (jogVelocity > 0) ? jogVelocity : 0;
				break;
			case ClientCommand::JogSub::Negative:
				cmd.nTargetVelocity = (jogVelocity > 0) ? -jogVelocity : 0;
				break;
			case ClientCommand::JogSub::Stop:
				cmd.nTargetVelocity = 0;
				break;
			default:
				break;
			}
		}

		return;
	}

	if (mainCmd != ClientCommand::Main::ControlDrive)
		return;

	const auto sub = static_cast<ClientCommand::DriveSub>(subRaw);

	for (int i = 0; i < kMotorCount; ++i)
	{
		ModorCmd& cmd = m_MotorCmdArea.Data[i];
		const MotorSt& st = m_MotorStArea.Data[i];

		switch (sub)
		{
		case ClientCommand::DriveSub::EnableSequence:
		{
			// Enable sequence 6 -> 7 -> 15 from status; hold CSP target at
			// actual position to avoid a jump on enable. Skip while a fault
			// flag is latched in the status word.
			if ((st.nStatusWord & humanoid::cia402::kStatusFaultBit) != 0)
				break;

			cmd.nTargetPosition = st.nActualPosition;

			const std::uint16_t sb = humanoid::cia402::StateBits(st.nStatusWord);
			if (sb == 0x0027U)
				cmd.nControlWord = humanoid::cia402::kControlEnableOperation;
			else if (sb == 0x0023U)
				cmd.nControlWord = humanoid::cia402::kControlEnableOperation;
			else if (sb == 0x0021U)
				cmd.nControlWord = humanoid::cia402::kControlSwitchOn;
			else
				cmd.nControlWord = humanoid::cia402::kControlShutdown;
			break;
		}
		case ClientCommand::DriveSub::QuitStep:
		{
			// Quit step: walk back from EnableOperation toward "not enabled"
			// one CiA 402 transition per cycle.
			const std::uint16_t sb = humanoid::cia402::StateBits(st.nStatusWord);
			if (sb == 0x0027U)
				cmd.nControlWord = humanoid::cia402::kControlSwitchOn;
			else if (sb == 0x0023U)
				cmd.nControlWord = humanoid::cia402::kControlShutdown;
			else if (sb == 0x0021U)
				cmd.nControlWord = humanoid::cia402::kControlShutdown;
			break;
		}
		case ClientCommand::DriveSub::FaultReset:
			// Only assert the fault-reset bit while an error code is latched.
			if (st.nErrorCode == 0)
				break;
			cmd.nControlWord = static_cast<USHORT>(cmd.nControlWord | humanoid::cia402::kControlFaultReset);
			break;
		default:
			break;
		}
	}
}

///////////////////////////////////////////////////////////////////////////////
void CModule::AdsReadWriteInd
(
	AmsAddr& rAddr, 
	ULONG invokeId, 
	ULONG indexGroup,
	ULONG indexOffset, 
	ULONG cbReadLength, 
	ULONG cbWriteLength, 
	PVOID pData 
)
{
	m_Trace.Log(tlVerbose, FENTERA_STRV("oid=0x%08x, invokeId=%d, indexGroup=0x%08x, indexOffset=0x%08x, cbReadLength=%d, cbWriteLength=%d, pData=0x%p",
		m_objId.value, invokeId, indexGroup, indexOffset, cbReadLength, cbWriteLength, pData));

	switch(indexGroup)
	{
	case ModuleIndexGroup1:
		switch(indexOffset)
		{

		case ModuleIndexOffset1:
			m_Trace.Log(tlInfo, FNAMEA_STRV("oid=0x%08x indexGroup=0x%08x, indexOffset=0x%08x",
				m_objId.value, indexGroup, indexOffset));

			// TODO: add custom code here

			AdsReadWriteRes(rAddr, invokeId, ADSERR_NOERR, 0, NULL); 
			break;

		case ModuleIndexOffset2:
			m_Trace.Log(tlInfo, FNAMEA_STRV("oid=0x%08x indexGroup=0x%08x, indexOffset=0x%08x",
				m_objId.value, indexGroup, indexOffset));

			// TODO: add custom code here

			AdsReadWriteRes(rAddr, invokeId, ADSERR_NOERR, 0, NULL); 
			break;
		}
		break;
	case ModuleIndexGroup2:
		switch(indexOffset)
		{

		case ModuleIndexOffset1:
			m_Trace.Log(tlInfo, FNAMEA_STRV("oid=0x%08x indexGroup=0x%08x, indexOffset=0x%08x",
				m_objId.value, indexGroup, indexOffset));

			// TODO: add custom code here

			AdsReadWriteRes(rAddr, invokeId, ADSERR_NOERR, 0, NULL); 
			break;

		case ModuleIndexOffset2:
			m_Trace.Log(tlInfo, FNAMEA_STRV("oid=0x%08x indexGroup=0x%08x, indexOffset=0x%08x",
				m_objId.value, indexGroup, indexOffset));

			// TODO: add custom code here

			AdsReadWriteRes(rAddr, invokeId, ADSERR_NOERR, 0, NULL); 
			break;
		}
		break;
	default:
		__super::AdsReadWriteInd(rAddr, invokeId, indexGroup, indexOffset, cbReadLength, cbWriteLength, pData); 
		break;
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STR());
}


void CModule::SubmitAdsReadReq()
{
	m_Trace.Log(tlVerbose, FENTERA_STR());
	// m_ContextAdsPort contains the ADS port number of the task associated with context 1
	// amsAddr refers to the ADS port of this task 
	AmsAddr amsAddr(this->AmsGetNetId(), m_ContextAdsPort);

	// Request the value of a parameter from a TwinCAT module instance
	// via the task ADS port.
	// The object id of the instance is passed as index group and
	// the parameter id is passed as index offset.
	// The result is delivered by a call to AdsReadCon and can 
	// be identified by the invoke id. 
	int nRes = 
		AdsReadReq
		(
			amsAddr, 
			invokeIdReadByOidAndPid, 
			m_objId.value, 
			PID_ModuleCounter,
			sizeof(m_ReadByOidAndPid)
		);
	if (nRes != ADSERR_NOERR)
	{
		m_Trace.Log(tlError, FNAMEA_STRV("AdsReadReq failed with error=0x%08x(%s)", nRes, AdsGetErrorText(nRes)));
	}
	else
	{
		m_Trace.Log(tlInfo, FNAMEA_STRV("AdsReadReq by oid=0x%08x and pid=0x%08x", m_objId.value, PID_ModuleAdsPort));
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STR());
}

///////////////////////////////////////////////////////////////////////////////
void CModule::AdsReadCon
(
	AmsAddr& rAddr,
	ULONG invokeId,
	ULONG nResult,
	ULONG cbLength,
	PVOID pData
)
{
	m_Trace.Log(tlVerbose, FENTERA_STRV("oid=0x%08x, invokeId=%d, nResult=0x%08x, cbLength=%d, pData=0x%p",
		m_objId.value, invokeId, nResult, cbLength, pData));

	if (invokeId == invokeIdReadByOidAndPid)
	{
		if (nResult != ADSERR_NOERR)
		{
			m_Trace.Log(tlWarning, FNAMEA_STRV("ReadByOidAndPid failed with error=0x%x(%s)",
				nResult, AdsGetErrorText(nResult)));
		}
		else if (cbLength == sizeof(m_ReadByOidAndPid))
		{
			m_ReadByOidAndPid = *static_cast<PULONG>(pData); 
			m_Trace.Log(tlInfo, FNAMEA_STRV("m_ReadByOidAndPid=0x%x", m_ReadByOidAndPid));
		}
	}
	else
	{
		__super::AdsReadWriteCon( rAddr, invokeId, nResult, cbLength, pData );
	}
	m_Trace.Log(tlVerbose, FLEAVEA_STR());
}
